---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: documents
  templates:
  - page-template
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - blog-post
- type: directory
  path: _news
  label: News
  create: documents
  match: "**/*"
  templates:
  - news-update
- type: document
  path: _data/awards.yml
  label: Awards
- type: document
  path: _data/media_hits.yml
  label: Media Hits
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
