backend:
  name: github
  repo: coolsoftwaretyler/shaleen-title
  branch: master

local_backend: true

media_folder: "img"
collections:
  - name: "pages"
    label: "Pages"
    create: true
    slug: "{{title}}.md"
    files:
      - name: "contact"
        label: "Contact Me"
        file: "contact.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "home"
        label: "Home"
        file: "index.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}.md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - { name: date, label: Date, widget: date }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "awards"
    label: "Awards"
    files:
      - name: "awards"
        label: "Awards"
        file: "_data/awards.yml"
        fields:
          - label: "Awards"
            name: "awards"
            widget: "list"
            fields:
              - {
                  label: "Award Description",
                  name: "award_description",
                  widget: "string",
                }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Highlighted", name: "highlighted", widget: "boolean" }
  - name: "media-hits"
    label: "Media Hits"
    files:
      - name: "media-hits"
        label: "Media Hits"
        file: "_data/media_hits.yml"
        fields:
          - label: "Media Hits"
            name: "media_hits"
            widget: "list"
            fields:
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Date", name: "media_date", widget: "string" }
              - { label: "Year", name: "year", widget: "string" }
